### ISSUE TITLE
Typescript implementation + stage getting initialized as null

### ISSUE THREAD

**Issue by jjohnsonatgm** [DevExpress/testcafe-example-multiuser-scenario#4]
Hi,

I've been trying to convert this repository to Typescript + integrating it into an existing TestCafe project. I've created a minimal representation of what I'm trying to do that shows the problem I'm currently experiencing and pushed it here:

https://github.com/jjohnsonatgm/testcafe_multiuser

Let me know if you cannot clone or access it and I can give you access even though it should be public.

Essentially what is happening is this:

```
Teacher Fixture for multi remote
Check page load
null
Check page load
null

   1) Error: Another stage was expected:
      expected: null
      tried: Check page load
```

I've tried a variety of methods of initializing scenarios in my student + teacher fixtures (in the test and outside of the test), but neither seem to work.

Also, it appears that only one browser is being spun up so something the way I reworked the scenario-gist.js file to work from a fixture file doesn't look like it's happy.

When is the testcafe team going to develop something like this: https://webdriver.io/docs/multiremote/ to make this process less painful 🥲? 

Let me know if you have any questions or any suggestions on how I can fix this.

Thanks!

**Comment by felis2803** [comment]
Hello @jjohnsonatgm,

This example was created for scenarios where you need to run several different browsers, or the same one, but with different options. If this is not required, then perhaps the built-in [Multiple Browser Windows](https://testcafe.io/documentation/402841/guides/advanced-guides/multiple-browser-windows) mechanism is more suitable for you. It's much easier to use and you won't have any problems with TS when using it.

**Comment by jjohnsonatgm** [comment]
Hi @felis2803,

The scenario that I'm trying to automate is this:

- Teacher logs into a portal and launches a "live mode" lesson
- Student logs in and sees a "live mode" pop up in their application
- Student joins the live lesson and starts a video
- Teacher has a "pause" button that pauses all students. Teacher presses that button.
- Student sees a "you're paused" modal display

All of this has to be done when both users are logged in and active at the same time.

From what I can see what your JS implementation works perfectly for the scenario as I need one "teacher" (non incognito Chrome) and one "student" (incognito) browser to be logged in at the same time.

Yeah I took a look at the Multiple Browser Windows mechanism and I don't think that would satisfy this use case? Although, I might be looking at it wrong. Originally, I had tried Roles but my users weren't being swapped when going from teacher -> student

Have you had an opportunity to take a look at the attached github repo I posted? I would appreciate any tips toward making that work if possible. The main issue that I appear to be having is that the my "stages" getting pulled from my student + teacher fixtures are sending "null" stages. Not sure if this is because I'm using a fixture rather than a "scenario-gist" setup?

Thanks!

**Comment by felis2803** [comment]
Hello @jjohnsonatgm,

If you want to write this example in TypeScript, then you can't do without a compiler. Note that in the original example, `scenarioGist` is a regular function (not a TestCafe test), and the entire example is run with the `node test` command.

**Comment by jjohnsonatgm** [comment]
Hi @felis2803,

I updated the repository posted in my first comment with compiled code (https://github.com/jjohnsonatgm/testcafe_multiuser). I believe this is what you told me to try in your comment "then you can't do without a compiler."

I also changed my npm command to run toward the build: 
`
"test": "node ./build/test/fixtures/main.test.js"
`

The null run stage problem is still occurring:

`
throw new Error("Another stage was expected:\n        expected: ".concat(this._expectedStageName, "\n        tried: ").concat(stageName, "\n    "));

Error: Another stage was expected:
        expected: null
        tried: Check page load
`

**Comment by felis2803** [comment]
https://github.com/jjohnsonatgm/testcafe_multiuser/blob/2858ae2615945161bf8da05e024f3e8945ad86f4/test/classes/scenario.class.ts#L17
This is an invalid operation. Check what you are getting into the `user` constant.

**Comment by jjohnsonatgm** [comment]
Hi @felis2803,

Thank you for the help! I was able to figure it out with your hints 😄 

If anyone comes behind me and finds this issue and wants to use this functionality in a Typescript framework feel free to use my repo as an example. I'll be leaving it public.
